### ISSUE TITLE
A problem about training Generator

### ISSUE THREAD

**Issue by HX-idiot** [sodabeta7/MetaGAN#3]
Hello, pleased to read your paper.  In MetaGan+RelationNetwork, when Generator produce fake Z, how to calculate P(y=N+1 | Z) in Discriminator? It seems you set the logit of fake class to 0, then P(y=N+1 | Z) is always a constant ? Then how to get gradient for training generator?

**Comment by sodabeta7** [comment]
To train the generator, you can use p(y=N+1 | x) = 1 - p(y<=N | x).

**Comment by HX-idiot** [comment]
Is it a mistake for the objective of Generator?  L_g=-E(...) , I don't think the '-' should exist.
<img width="679" alt="2018-12-13 5 50 34" src="https://user-images.githubusercontent.com/38073340/49930596-e791ae80-feff-11e8-93cc-0ee4486610aa.png">
